name: autoapprove
author: casconem
description: Auto-approve pending jobs when `require<Env>Approval` is set to false in the config_data object.

inputs:
  env_to_approve:
    description: The environment name to approve
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo "Deploy to ${{ inputs.env_to_approve }} Auto Approved"    >> $GITHUB_STEP_SUMMARY
        echo "Run triggered by: $GITHUB_TRIGGERING_ACTOR" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Get Environment ID
      id: environment-id
      shell: bash 
      run: |
        envs=$(gh api repos/$GITHUB_REPOSITORY/environments)

        envID=$(echo $envs | jq -r '.environments[] | select(.name=="${{ inputs.env_to_approve }}") | .id')
        echo "ENVID=$envID" >> $GITHUB_ENV

    # only approve if there are pending deployments in the current run
    - name: Get Pending Deployments
      id: pending-deployments
      shell: bash
      run: |
        result=$(gh api repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments)

        pending=false
        if [[ "$result" != '[]' ]]; then
          pending=true
        fi

        echo "PENDING=$pending" >> $GITHUB_ENV

    - name: Approve Pending Deployment
      if: env.PENDING == 'true'
      shell: bash
      run: |
        gh api -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28"         \
          --method POST                                 \
          -F "environment_ids[]=$ENVID"                 \
          -f "state=approved"                           \
          -f "comment=Auto-Approved by GitHub Actions"  \
          repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments
