name: conditions tester

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    outputs: 
      runDev: ${{ steps.set_output.outputs.runDev }}
      runProd: ${{ steps.set_output.outputs.runProd }}

    steps:
      - name: Run tests
        run: echo "Running init"

      - name: set output
        id: set_output
        run: echo "runDev=true" >> $GITHUB_OUTPUT
  
  deployDev:
    runs-on: ubuntu-latest
    name: Deploy to DEV
    environment: DEV
    needs: init

    if: ${{ needs.init.outputs.runDev == 'true' }}
    
    steps:
      - name: deploy dev
        run: echo "Deploying to DEV" >> $GITHUB_STEP_SUMMARY

  deployProd:
    runs-on: ubuntu-latest
    name: Deploy to PROD
    environment: PROD
    needs: [init, deployDev]

    if: ${{ needs.init.outputs.runProd == 'true' }}

    steps:
      - name: deploy prod
        run: echo "Deploying to PROD" >> $GITHUB_STEP_SUMMARY
